### ISSUE TITLE
Re-added Lady birthsign attribute bonuses

### ISSUE THREAD

**Issue by luthis1124** [Clavernever/Gentler_Racemenu#2]
Unsure if this is because I added Birthsigns Are More Fun (BAMF) at the same time as adding this to my load order,

When I checked it had correctly added everything back, but had added the Lady attribute increases again.

**Comment by Clavernever** [comment]
If you changed mods (adding something on top of vanilla counts as such) and that mod changes the birthsign spell's name, then it's not going to recognise the previous spell and therefore won't delete it (it'll see it as an ability you got from some other source, such as a quest, vampirism etc, since it doesn't know it's a birthsign anymore).
If me (or anyone else) makes the mod remember birthsign data across game saves, then the issue would go away.
I am planning to support mod changing at some point, but haven't managed the time to get to it yet.

Edit: yes, just checked and that's exactly what it does, it changes Lady's spells, causing GRM to think the vanilla one isn't a birthsign anymore.

**Comment by Clavernever** [comment]
Should be fixed on the new version.
I presume you've long moved on, but still here's how it works:

Now you can port a character from vanilla -> modded races/birthsigns, or between two supported mods.
Load your save _before_ changing your plugins, go to settings and follow the instructions under "Migration Mode"

If you haven't done that, you could still at least fix your spells by running EnableStatReviewMenu with "Purge Spells" enabled. Currently Purge Spells is a bit limited (only works for Vanilla and Reincarnate/Moonlight spells), but is still worth trying.
